name: boycott_alert
description: A Flutter app that detects boycott brands from speech

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.3.0
  audioplayers: ^4.0.1
  flutter_background_service: ^4.0.1
  permission_handler: ^10.4.0
  vibration: ^1.7.5
  flutter_local_notifications: ^15.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alarm.mp3